version: "3.9"
services:
  neo4j:
    image: neo4j:3.5.8
    hostname: neo
    container_name: neo4j
    expose:
      - 7474
      - 7687
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=$NEO4J_CREDENTIALS
      - NEO4J_INTERNAL_URL=$NEO4J_INTERNAL_URL

  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=S3cret
