version: "3.9"
services:
  neo4j:
    image: neo4j:4.4
    hostname: neo
    container_name: neo4j
    networks:
      backend:
        ipv4_address: 172.21.0.2
    expose:
      - 7474
      - 7687
    volumes:
      - .:/data/
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=$NEO4J_CREDENTIALS
      - NEO4J_INTERNAL_URL=$NEO4J_URL
      # install plugins
      - NEO4JLABS_PLUGINS=["graph-data-science"]
      - NEO4J_dbms_security_procedures_whitelist=gds.*
      - NEO4J_dbms_security_procedures_unrestricted=gds.*

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - 27017:27017
    expose:
      - 27017
    networks:
      backend:
        ipv4_address: 172.21.0.3

  api:
    build: .
    expose:
      - 80
    ports:
      - "80:80"
    depends_on:
      - neo4j
      - mongo
    networks:
      backend:
        ipv4_address: 172.21.0.5
    container_name: api
    command:
      sh -c "python3 -u populate_mongo.py && python3 -u app.py"
      # && python3 -u createGraph.py
      # sh -c "python3 -c'from Neo4J import NeoDatabase; NeoDatabase.createProjection()'"

networks:
  backend:
    driver: bridge
    name: network_backend
    ipam:
      driver: default
      config:
        - subnet: "172.21.0.0/24"
          gateway: 172.21.0.1
